# Generated by Django 3.1.3 on 2022-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20220827_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(default='Choice text here', max_length=550),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='Question text here', max_length=550),
        ),
    ]
